FROM python:3.12-slim

WORKDIR /app

COPY requirements.ui.txt .

RUN pip install --no-cache-dir -r requirements.ui.txt

COPY src/ ./src/

EXPOSE 8501

CMD ["streamlit", "run", "src/ui/app.py", "--server.address=0.0.0.0", "--server.port=8501"]